### ISSUE TITLE
chore: Update image in local helm chart

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1188]
When running `helm install kargo ./charts/kargo`, the installation still uses the `v0.1.0` image. This causes errors when applying Kargo resources as much has changed since 0.1.0

**Comment by krancour** [comment]
Ah...

So `v0.1.0` was just a placeholder. (It didn't let me do v.0.0.0. I tried!) The release process inserts the correct version number.

But if you use `helm install kargo ./charts/kargo`, you're getting stuck with that placeholder. ☹️ 

I don't typically encounter this because I'm using Tilt and it automatically builds images, pushes them to a local registry, and updates the rendered YAML from `helm template ./charts/kargo`, setting the image version correctly, _by digest_.

I suppose the bug here may not actually be a matter of changing that placeholder, but more a matter of having a convenient way (besides Tilt?) of "shimming" a locally built, un-official image into the chart for development purposes.

**Comment by krancour** [comment]
I think we agreed that the release process sets this value properly and during development Tilt seamlessly handles shimming a locally built image into the chart. When Tilt was slower, I could see an alternative method of accomplishing that shimming as being needed, but #1248 resolved slowness issues. I don't think we can build a more seamless way of doing what Tilt is doing for us, so I am tentatively closing this.
