### ISSUE TITLE
UI needs a way to determine freight ID (after aliases were added)

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1197]
# Description

I want to know the freight ID (hash), because I want to find the corresponding CR in my namespace. But UI has no way of finding it after aliases were introduced.

# Screenshots

<img width="452" alt="image" src="https://github.com/akuity/kargo/assets/12677113/1347407b-5216-470d-93b4-432f0efb2ffc">

# Version

Tip as of today

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
Mouseover... added earlier today. Problem is it's not obvious you can do that.

**Comment by krancour** [comment]
@rbreeze do you think if the alias were styled like a link it might prompt people in search of more info to mouseover?

**Comment by rbreeze** [comment]
I think that may be a question @jessesuen could answer better: would an underline have helped you discover it?

An underline wouldn't be my first choice in this case, as IMO it would add a lot of visual cruft since it would affect every alias label. But at the same time, I can't think of a better way to make it clearer.

Two more thoughts:
1. Clicking the alias should copy the ID (or at least, there should be an action menu item to copy the ID)
2. The Kargo CLI should have a feature to allow getting Freight by alias

**Comment by krancour** [comment]
> Clicking the alias should copy the ID (or at least, there should be an action menu item to copy the ID)

Love that idea.
