### ISSUE TITLE
UI: Click on Warehouse in DAG to select view of a specific Freightline

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1208]
See comments here: https://github.com/akuity/kargo/discussions/1156#discussioncomment-7689380

**Comment by krancour** [comment]
Related to #1680 

I will challenge the idea of "filtered view of Freightline" since that implies Freight from multiple warehouses being present in one single Freightline and I think we're sure we want multiple _distinct_ Freightlines instead.

Clicking a Warehouse so _select a Freightline_ (rather than filter) seems like a reasonable way of implementing a "Freightline picker."

Adding this t v0.6.0.

**Comment by krancour** [comment]
I think we would also need to change which specific Freightline is shown in response to clicks on Stages as well. Each Stage consumes Freight that originated from a specific Warehouse. When you start a promotion to a specific Stage or to all subscribers of a Stage, I believe we'd need to automatically update which Freightline we show so that it's populated with the relevant Freight for the Stage(s) in question.
