### ISSUE TITLE
Add RBAC for manually approving Freight to a Stage

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1222]
# Proposed Feature

We introduced the ability to approve freight for a certain stage. This needs to be protected by RBAC. 

# Motivation

Manual approving freight should be considered a privilege similar/or same as to promoting.

# Suggested Implementation

In our RBAC webhook check, we should perform the same check we do for promote against a freight, making sure user has the `promote` privilege for stage, if we notice that the user is modifying a Freight for a certain stage.

**Comment by krancour** [comment]
Besides adding this to the webhook, we also have to check for it explicitly in the API server.

Typically, we don't need to do that, but in this case we do.

The API server's _own_ kube client has a wrapper around it that does a subject access review to assert the user's ability to perform a specific action. If that passes, the API server carries out the action using its own client. This allows us to never miss out on the benefits of the client's cache.

The tricky thing here is that the call the API server will be making is a _patch_ call on Freight Status, but we want to gate that on permissions for the virtual "promote" verb on a given Stage. This out-of-the ordinary misalignment of both resources and verbs is what requires us to check for this explicitly in the API.

Now that I think of this, the API server _also_ needs to do this for Promotions as well, but currently does not. Again, there's a misalignment because of both resources and verbs. Creation of a Promotion resource needs to be gated on permissions for the virtual "promote" verb on a given Stage.

**Comment by krancour** [comment]
This doesn't look like it will make it into v0.3.0. Deferring to v0.4.0.

**Comment by krancour** [comment]
> In our RBAC webhook check, we should perform the same check we do for promote against a freight

> Besides adding this to the webhook, we also have to check for it explicitly in the API server.

Approval is an imperative that causes the back end to update Freight status with information about what Stages it is approved _for_.

Status sub-resources can not be updated declaratively by users. They can be _patched_ if one has proper permissions, but:

1. Webhooks cannot intercept patch operations.
2. User would not typically be granted permission to update or patch status sub-resources.

@jessesuen or @hiddeco I wouldn't mind a sanity check on that.

If I am right, the only change required here is in the API server, with no webhook changes required.

**Comment by krancour** [comment]
> Isn't a status patch just an "UPDATE" operation to the freight/status resource?

I don't _think_ so, but I will find out definitively.

**Comment by hiddeco** [comment]
Based on my current understanding, I _think_ your observations are correct.

**Comment by krancour** [comment]
In that case, #1570 should tick all the necessary boxes for this issue.
