### ISSUE TITLE
all cli commands fail if config file doesn't exist already

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1341]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Running `kargo version` when you're not logged in returns an error

Example

```shell
$ kargo version
Error: get version info from server: unavailable: unsupported protocol scheme ""
```

# Steps to Reproduce

First:

```
rm -rf ~/.config/kargo
```

Then 

```
kargo version
```

# Expected behavior

There should be a `--client` flag that returns the version of the client when not logged into a Kargo server

Example:

```
kargo version --client
```

**Comment by krancour** [comment]
It's not just `version`. It's actually _all_ commands that fail with this if you don't have an existing config file. Even `login` fails.

It appears to have been introduced in #1179 

cc @devholic

**Comment by bygui86** [comment]
Hi @krancour when do you plan/think to release kargo cli v0.3.1 to fix this issue?
It's quite critical as it's not possible to test the [quickstart guide](https://kargo.akuity.io/quickstart) because not possible to create any project.
Is there an alternative way to create a Kargo Project? maybe YAML?

**Comment by krancour** [comment]
@bygui86 I expect v0.3.1 to be released today.
