### ISSUE TITLE
Add ownerReferences to AnalysisRun objects

### ISSUE THREAD

**Issue by daftping** [akuity/kargo#1395]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature
Add ownerReferences to AnalysisRun objects.

# Motivation

- Allow Argo CD to detect and visualize these objects. 
- Implement cascading deletion when the stage is deleted.

# Suggested Implementation
Add Stage as an owner of the AnalysisRun.

**Comment by krancour** [comment]
Hi @daftping. Thanks for the suggestion. I'd actually love to be able to set this, but this won't work for all topologies.

There is flexibility built into the controller to deal with up to three different Kubernetes clusters:

* One where the Kargo control plane runs
* One where Argo CD runs
* One where Rollouts runs

Any two, or even all three, could be the same cluster.

Kargo Stages always live in the Kargo control plane, but often, that won't be a suitable place for executing user-defined functionality, meaning those controllers execute AnalysisRuns elsewhere.

We can't really do object ownership across clusters. ☹️

**Comment by daftping** [comment]
I'd assume having all three (Kargo, Argo CD and Argo Rollouts) at one cluster would be the most common topology.
Would it still make sense to set ownerReferences only If Kargo and Argo Rollouts are on the same cluster?

**Comment by krancour** [comment]
> I'd assume having all three (Kargo, Argo CD and Argo Rollouts) at one cluster would be the most common topology.

I'm guilty of having called that the common case before. I actually stopped myself from writing it in my previous response because I'm increasingly dubious of that being the case.

> Would it still make sense to set ownerReferences only If Kargo and Argo Rollouts are on the same cluster?

I'd rather solve for this one way than two.

Something like adding a finalizer to Stages to ensure cascading deletion of Stage-specific resources (across all applicable clusters) seems it would be a universal solution.

fwiw, I 100% agree that deleting a Stage should take related things with it. It's just implementation details to work out.

The garbage collector also still needs to learn how to clean up AnalysesRuns.

**Comment by daftping** [comment]
Having consistency between different topologies is more reasonable.
I was more interested in better observability than cleanup.
Not having an Analysis status in Kargo UI, makes it hard to see the results.
Since we are planning to track Kargo objects as an Argo CD App as well, I was hoping users could use Argo CD UI to see AnalysisRun executions. However, it is easily can be a workaround by clicking "Show Orphaned" in the UI and still seeing the AnalysisRun objects created by Kargo.

**Comment by krancour** [comment]
> Not having an Analysis status in Kargo UI, makes it hard to see the results.

That's coming. UI features are lagging behind the back end by a bit.

**Comment by jessesuen** [comment]
Based on some recent discussions/developments, the current thinking is shifting to to keep AnalysisRuns in the same cluster as the Stage, since Rollout can be improved in ways to operate against them remotely. So, given that direction, we may be able to assume Stages and Runs live in the same cluster and then this feature request makes complete sense.

**Comment by krancour** [comment]
Based on recent discussions, I agree.

**Comment by krancour** [comment]
Thinking about this more, I'm not sure it's clear that AnalysisRuns _should_ belong to a Stage -- or at least maybe it shouldn't belong _exclusively_ to it.

Considerations:

* AnalysisRuns are used to verify _Freight WRT a specific Stage_. From that perspective, it could be argued that it should be co-owned by both of those.

* Since AnalysisRuns are spawned from AnalysisTemplates, it could also be argued that the AnalysisTemplate is a third owner of an AnalysisRun. (@jessesuen does the Rollouts Controller make AnalysisTemplates owners of AnalysisRuns?)

* If one thinks of ownership purely in terms of if/how deletes should cascade, it could be argued that the Freight should be the _only_ owner since old/unused Freight should be GC'ed periodically (it isn't currently) and we wouldn't want longer-lived things like Stages and AnalysisTemplates standing in the way. (k8s docs state that deletes cascade to a resource only when its _last_ owner is deleted.)

So while I agree there is _some_ kind of ownership relationship we should probably be establishing here, it's not clear to me what the _right_ one is.

The third option seems most correct to me, _but_ @daftping mentioned an observability component to that may not be served well by that option. 🤷‍♂️ 

@jessesuen or @hiddeco do either of you have any thoughts?

**Comment by hiddeco** [comment]
> Since AnalysisRuns are spawned from AnalysisTemplates, it could also be argued that the AnalysisTemplate is a third owner of an AnalysisRun.

I do not think this would be the right approach, as the template appears to be only used to derive the configuration for an AnalysisRun. The actual spawning is done for the Stage, which compared to core Kubernetes functionalities looks more like a ReplicaSet spawning a Pod based on an an external template (where ReplicaSet owns the Pod).

In addition, you mention AnalysisTemplates are "longer lived" than the runs, but they also have their own life-cycle outside of the Stage and AnalysisRun. Adding an owner reference would imply that changes (including a deletion of the template) would invalidate the run result, which I think isn't necessarily true (instead, the desires from a Stage for any new AnalysisRun may have just changed).

> If one thinks of ownership purely in terms of if/how deletes should cascade, it could be argued that the Freight should be the _only_ owner since old/unused Freight should be GC'ed periodically

But this leaves the question what would happen if a Stage is deleted? Based on my current understanding, this should in theory also cause a cascade delete for any AnalysisRun produced for this Stage (while the Freight may actually continue to live on in the Warehouse or in another Stage). Which kind of presents an inverse of "Stages and AnalysisTemplates standing in the way", as you wouldn't be able to do this when its co-ownership is with the Freight...

**Comment by krancour** [comment]
>> Since AnalysisRuns are spawned from AnalysisTemplates, it could also be argued that the AnalysisTemplate is a third owner of an AnalysisRun.
>
> I do not think this would be the right approach

I didn't necessarily think it was. I was more curious about what ownership relationships, if any, Rollouts creates.

>> If one thinks of ownership purely in terms of if/how deletes should cascade, it could be argued that the Freight should be the only owner since old/unused Freight should be GC'ed periodically
>
> But this leaves the question what would happen if a Stage is deleted? Based on my current understanding, this should in theory also cause a cascade delete for any AnalysisRun produced for this Stage (while the Freight may actually continue to live on in the Warehouse or in another Stage). Which kind of presents an inverse of "Stages and AnalysisTemplates standing in the way", as you wouldn't be able to do this when its co-ownership is with the Freight...

Yes. I agree that if a Stage is deleted, any AnalysisRuns associated with it can be deleted as well. I didn't adequately account for that, so thank you for calling it out.

Here's what I propose:

* The thing is that I expect deletion of old/unused Freight by the Kargo GC to be a much more common event than deletion of a Stage. Also, there is no Freight reconciler. If we make Freight the sole owner of an AnalysisRun, we'll get complimentary AnalysisRun cleanup from k8s when a Freight is deleted. The Stage still existing won't stand in the way.

* There _is_ a Stage reconciler and there's already a finalizer on Stages. We can amend the reconciliation process for Stage deletions to delete all AnalysisRuns associated with the Stage. (Which should be easy because they're already indexed, iirc.)

This makes sense to _me_ and I think of it as a step in the right direction, but also is incongruous with the original request:

> Add Stage as an owner of the AnalysisRun.

But OP also stated:

> I was more interested in better observability than cleanup.
> Not having an Analysis status in Kargo UI, makes it hard to see the results.

This is coming. (https://github.com/akuity/kargo/issues/1284)

> Since we are planning to track Kargo objects as an Argo CD App as well, I was hoping users could use Argo CD UI to see AnalysisRun executions.

This is inconsistent with overall product direction. We want all the high level stuff at your fingertips in the Kargo UI and for users to only "drop down" to Argo CD for troubleshooting lower-level problems.

@hiddeco what do you think?

**Comment by hiddeco** [comment]
> I didn't necessarily think it was. I was more curious about what ownership relationships, if any, Rollouts creates.

I didn't assume you were thinking this, I was more trying to reason further about it myself while providing a proper explanation why it wouldn't be the case. So I think we are aligned here 😄 

---

I think your proposal matches the direction I was headed towards myself, but I do think there is a gap to bridge before we can actually get there.

As at present, it appears Stages are indexed by AnalysisRun instead of the other way around. While at the same time, an AnalysisRun can only be looked up by Stage if it's part of the VerificationInfo for the current Freight. Due to this, previous AnalysisRuns can not be tracked, and would not be caught by the garbage collector until the Freight is orphaned by any other Stage(s).

While based on your comments around expectations this is potentially something which can be ignored. It makes me cautious about proceeding with this approach without thinking it over once again.
