### ISSUE TITLE
bug: app sync error not being factored into stage health

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1451]
@jessesuen pointed out some time ago that some applications exist in a state of perpetual drift, and as such, when determining stage health, we transitioned from looking at sync state to simply verifying sync was complete as evidenced by lack of an operation...

This has worked relatively well, _but_ the change doesn't account for the possibility that there was an _error_ syncing. So the scenario I am running into now is that syncing has complete, but with an error. No resources exist within the app, so Argo CD judges the App to be healthy. Kargo sees a healthy App with no pending operation and thinks all is well.

The change I propose is this:

Return to looking at sync state. If it's synced, great. If it's completed with an error, factor this into stage health. If it's in-progress, _then_ look at whether there is a pending operation or not.

@jessesuen can you sanity check my thought process here before I moved ahead with the fix?

**Comment by jessesuen** [comment]
> Return to looking at sync state. If it's synced, great. If it's completed with an error, factor this into stage health. If it's in-progress, then look at whether there is a pending operation or not.

I'm not sure I'm following the proposal. Argo CD terminology is regrettably confusing (we overused the term sync), so I would like to clarify some of the statements. Argo CD has the following:

* Sync status - a living status whether or not the app is `Synced` or `OutOfSync` with git. Earlier we decided Sync status was irrelevant to Kargo because we can have apps that are perpetually OutOfSync.
* Health status - a living whether or not the application is healthy. Health can flip at any time (e.g. pod restarts). One of: `Progressing`, `Healthy`, `Suspended`, `Degraded`. Health status is relevant to Kargo because we need an application to reach Healthy in order to consider the stage verified
* Operation phase - the phase of the current or last sync operation. This is either `Terminating`, `Failed`, `Error`, `Succeeded`. Kargo does not currently examine operation phase, but I think you are proposing that it should.

This statement is what confused me:
> Return to looking at sync state. If it's synced, great. If it's completed with an error, factor this into stage health. 

I think you are referring to operation phase, since you used the term "completed". But you also referred to it as sync state.

If you are suggesting we start factoring operation phase into the equation, I agree that it may address the issue.

Here's what I'm thinking.
* I still don't think Sync status has any bearing on Kargo and can be ignored.
* A Stage's Health status is a direct mirror of application health status
* Stage's phase is affected by Application Health Status + Operation Phase

Waiting for an application to become healthy after a sync, IMO, is considered verification, but *not* part of Stage health. I would say waiting for app to become health is like waiting for the analysis run to complete Successful, in that regard.

Here is what I would do:
* Kargo promotes a Freight into a Stage. Stage is now Promoting
* Promotion job completes Successful. The Stage is now Verifying
* The Stage is Verifying indefinitely until:
    * There is no running operation. IMO, if there is a running operation we must to wait for it to complete
    * The app is no longer Progressing
* If there is no`Running` operation and app health is `Degraded` or `Healthy`, the Stage is back at a `Steady` state. 

The key difference in what I'm proposing, and what you are proposing, is that I would like for Stage health to be a mirror of the underlying health. Whereas I think you are proposing that the last operation factors into Health. Instead of the failed operation reflected into Stage Health, I think this should be indicated/surfaced in some other way to the UI that something is wrong.

**Comment by jessesuen** [comment]
There is one more idea I had: today, a Promotion is immediately successful if it triggered the Sync operation. But now that we have long-lived promotions, I actually feel it may be better to let the Promotion job keep running until the Sync operation is complete. And then the Promotion job should fail if the operation fails. At that point it is very visible in the UI.

This becomes especially more important as Kargo supports other things than Argo CD (e.g. terraform), I think we need the promotion job to act as the long pole in this, abstracting away all the waiting that currently resides in the Stage reconciler.

**Comment by krancour** [comment]
@hiddeco I'm tentatively reassigning this to you since it's intertwined with #1613, which you are already working on.
