### ISSUE TITLE
Kargo CLI should have a --client option

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1511]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The Kargo CLI command `kargo version` doesn't return the version of the CLI if there is no connection to the server. This comes up for me when there is a "stale" connection still cached.

Example

```shell
$ kargo version
Error: get client from config: error refreshing token: your token is expired; please use `kargo login` to re-authenticate
$ rm -rf ~/.config/kargo
$ kargo version
Client Version: v0.4.0
```

# Steps to Reproduce

1. Have a "stale" login creds under `~/.config/kargo`
2. Download Kargo CLI v0.4.0
3. Run `kargo version`

# Version

```
Client Version: v0.4.0
```

# Enhancement Proposal

There should be a `--client` option that just displays the version of the cli, bypassing the server version check.

Example

```shell
$ kargo version
Error: get client from config: error refreshing token: your token is expired; please use `kargo login` to re-authenticate
$ kargo version --client
Client Version: v0.4.0
```

**Comment by krancour** [comment]
Agree. And besides that, when `--client` isn't specified, we should print CLI version info _before_ handling any connection errors so that you at least see part of what you were looking for.

@hiddeco would you be willing to take this as another "warm up?" If so, know that there's an open issue for a more comprehensive CLI overhaul, so don't worry about making this perfect. Just make it work.
