### ISSUE TITLE
Support for OIDC google groups

### ISSUE THREAD

**Issue by mcatany** [akuity/kargo#1793]
# Proposed Feature

Hi, we're trying to deploy Kargo with ArgoCD with the helm chart. We have succesfully enabled SSO but know we face the problem of giving credentials for users at Google group level. We will like to do the same that that we did with ArgoCD [openid-connect-plus-google-groups-using-dex](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-plus-google-groups-using-dex), we don't don't find a way to add the volums with the helm chart on the dex-server. Is this going to be available anyway soon?

We tried adding the volume manually in the dex-server deployment and it the SSO worked perfectly with group levels.

**Comment by krancour** [comment]
Hi @mcatany!

I think this should already be achievable by setting these:

https://github.com/akuity/kargo/blob/9bd8d42138da2d55515dd4757c5fb0b4d6608d03/charts/kargo/values.yaml#L191-L197

https://github.com/akuity/kargo/blob/9bd8d42138da2d55515dd4757c5fb0b4d6608d03/charts/kargo/values.yaml#L209-L228

**Comment by mcatany** [comment]
Hi @krancour. Thanks for the quick response. I think from DEX [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-using-dex), it explicitly says that it cannot be used to achieve Groups claim.
![image](https://github.com/akuity/kargo/assets/40259268/20c8e67a-a1dc-41a9-aa76-8264930a8750)

**Comment by krancour** [comment]
One comment... Kargo isn't Argo... so just keep that in mind when looking at docs. ymmv

It seems what you're running into here is a limitation of the Google connector where it _can't_ take 100% of its configuration directly from its own `config.yaml` (including env vars referenced therein).

So I see what your problem is now...

I would reframe this _not_ as a request to support Google groups. Rather, I would frame this as a more generic feature for mounting arbitrary volumes to the Dex server -- in much the same way as we already permit creating arbitrary env vars on the Dex server.

That sounds perfectly doable. I'll open a new issue for that later today to replace this one and will leave this one open in the meantime.

**Comment by mcatany** [comment]
Thanks,

Yes, it's absolutely about just having the freedom to add volumes like it's already done by envars.

Thanks for the attention.

BR

**Comment by krancour** [comment]
Superseded by #1805
