### ISSUE TITLE
json_name on protobuf message fields not respected

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1916]
As an example:

https://github.com/akuity/kargo/blob/9097a9efafe14c135526508e532e4aeda6f91ceb/api/service/v1alpha1/service.proto#L381

https://github.com/akuity/kargo/blob/9097a9efafe14c135526508e532e4aeda6f91ceb/pkg/api/service/v1alpha1/service.pb.go#L3111

@devholic you are probably the best person to investigate this.

**Comment by devholic** [comment]
@krancour 

This is because golang protobuf package depends on json field in `protobuf` struct tag for the backward compatibility (https://github.com/golang/protobuf/issues/1307#issuecomment-809811088)

Using `google.golang.org/protobuf/encoding/protojson` instead of `encoding/json` will fix this issue and also can prevent potential failure while encoding well-known types (e.g. `google.protobuf.Timestamp`).: 
https://github.com/akuity/kargo/blob/c6d0a6d600a3a3a5e8b9d04816b60fb8d2fd4b4c/internal/cli/cmd/version/version.go#L143

(Kubernetes types (Kargo API types) should keep use `encoding/json` since they depend on `gogo/protobuf` features)

**Comment by krancour** [comment]
Thanks @devholic. I've put more thought into this and realize we really shouldn't be hung up over field names in protobuf messages anyway, as they're never really supposed to be seen. So... I went and fixed the problem that was making these snake_case fields bleed through in the CLI. See #1917.

I think we can close this.
