### ISSUE TITLE
Freight creation validating webhook

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2117]
# Proposed Feature

Today we have a validation webhook that makes Freight immutable. However, it is still possible that the Create Resource API allows someone to create Frieight that:
* may not include an item from each Warehouse subscription
* may include arbitrary images git commits not in the repositories referenced in the Warehouse

Kargo should improve the validation webhook to ensure the above scenarios are rejected during freight creation.

# Motivation

This is a security feature to ensure only things that are intended to be created by the Warehouse are allowed.

# Suggested Implementation

Add checks in validation webhook. Note that we only need to validate create, since we already have a webhook that makes Freight immutable.

**Comment by hiddeco** [comment]
One potential issue I see with confirming that the Warehouse has seen the Git commit, is that it potentially creates an issue when the Warehouse refreshes _while_ the user is dealing with the construction of the Freight it wants to create.

This could cause the Warehouse to no longer have a reference to the commit by the time the validation webhook is triggered, while their input was correct at the point of crafting the Freight.

Because of this, I continue to wonder if this would not result in confusion or an unpleasant user experience, and if this level of strictness is required.

**Comment by krancour** [comment]
I don't think we need to confirm that it is a commit, tag, etc. that the Warehouse has previously seen during discovery. I think we just need to validate that all the artifacts in the Freight are from a repo that the associated Warehouse actually subscribes to.
