### ISSUE TITLE
chore: use slices package instead of sort package

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2231]
Since Go 1.21, the `slices` package contains the preferred sorting implementations. Per Go documentations, they are both more ergonomic and more performant.

This issue calls for remediating existing `sort.X()` function calls by replacing them with their `slices.X()` equivalent.

**Comment by ankitsridhar16** [comment]
I can take a look and work on this

**Comment by hiddeco** [comment]
Thanks for your interest @ankitsridhar16!

> Can you provide additional details?

A lot of (if not, all) things that make use of `sort` functions[[1]], should be rewritten so they use their [`slices` counterparts](https://pkg.go.dev/slices).

[1]: https://github.com/search?q=repo%3Aakuity%2Fkargo+sort+language%3AGo&type=code&p=2&l=Go

**Comment by nitishfy** [comment]
hey @hiddeco, i've tried implementing the solution for it. I'm getting stucked at how are we going to use the `slices` package in order to sort based on a function, like [here](https://github.com/akuity/kargo/blob/3e008c94c3c3b49f59cde241314f63f55bd6d524/internal/api/list_stages_v1alpha1.go#L34)?

We can use the `slices.SortFunc()` for this, however, the internal implementation of `SortFunc` returns an int rather than bool value. Any suggestions here?

**Comment by hiddeco** [comment]
As `slices.SortFunc` documents:

> cmp(a, b) should return a negative number when a < b, a positive number when a > b and zero when a == b.

This means you can use the [`Compare` method on `time.Time`](https://pkg.go.dev/time#Time.Compare):

> If t is before u, it returns -1; if t is after u, it returns +1; if they're the same, it returns 0.

**Comment by nitishfy** [comment]
Gotcha! Please assign this issue to me, I'll fix it.
