### ISSUE TITLE
multi-pipelines: origin needs to be factored into freight id

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2240]
I set up two warehouses today where both looked for manifests in the same repo -- one using `includePaths: [microservice-a]` and the other using `includePaths: [microservice-b]`.

Because the most recent commit had changes to _both_ paths (it was an initial commit), both warehouses calculated the same Freight name and only one piece of Freight was produced. That piece of Freight had `origin: {kind: Warehouse, name: microservice-a}`.

The result is that Stages requesting Freight from `origin: {kind: Warehouse, name: microservice-b}` could not have that request fulfilled.

If we factor origin into each piece of Freight's deterministically calculated name, these conflicts will not occur.

cc @hiddeco for a sanity check.

**Comment by hiddeco** [comment]
For the record: I think your reasoning adds up here.

I did wonder for a bit if there are any potential downsides of the "deduplication" not happening (i.e. two Warehouses producing the same Freight because they ship the same items), but I think we are at a point where it has become clear that Freight is unique to its origin, and not necessarily just the contents.

**Comment by krancour** [comment]
This was fixed in #2241, but remained open because the feature branch its in has not been merged to main yet.

#1680 is the epic that we'll close when that happens.

I think we can safely close this as completed.
