### ISSUE TITLE
UI: Better support for multiple freight in one DAG node

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#2302]
With multi-pipelines support, one Stage node can contain multiple pieces of Freight. Currently when this happens, although it is supported and legible, it isn't the prettiest.

**Comment by danielloader** [comment]
Glad this has been noticed and worked on - found this in 0.8.0-rc.1 today.

My question would be just how this is going to be tackled? 
- Make the node just vertically taller to have more freight visible?
- Make a state node a container of smaller nodes if there's multiple freight in it? 
- Attach the lines from the warehouses to the freight inside the node rather than the node itself?

When working with anywhere between 3-12 warehouses feeding a stage today when experimenting I was trying to work out how I'd want this visually displayed and all the options seemed quite visually dense.

In addition to this, given the fact you can have multiple stages loosely grouped together vertically I can't even suggest a Trello style column to represent each stage so that pipelines could be fully parallel left to right and only show the freight name as a card in a column. 

I'm just trying to work out the best way to handle projects/warehouses and mapping them to business domains - I have 12 microservices that exist in a single business domain and thus looked after by a single team so I'm instinctively leaning towards a Project in Kargo being 1:1 mapped to a team, as a Project seems to be the physical manifestation of the access control system.

Happy to give more feedback if needed.

**Comment by krancour** [comment]
> I'm just trying to work out the best way to handle projects/warehouses and mapping them to business domains - I have 12 microservices that exist in a single business domain and thus looked after by a single team so I'm instinctively leaning towards a Project in Kargo being 1:1 mapped to a team

There's no "right way," but that's perfectly sensible.

> as a Project seems to be the physical manifestation of the access control system.

Yes. That is quite literally true. There is a 1:1 between Projects and Project namespaces. Permissions within a Project are just normal Roles, Rolebindings, etc. within the Project's namespace.

I think I recently mentioned on Discord that the UI is still catching up to the multi-pipelines feature, which is obviously very new. It will get better.

Something I'll mention though, in case it helps you to organize better in the meantime, please don't feel as if you _must_ use multi-pipelines or that you _must_ push it to extremes. Again, there's no "right way," and you have a lot of freedom in how your organize your Projects.

You gave an example of a dozen different microservices belonging to a single team. It _might_ not be necessary to manage delivery of all 12 microservices using a single, common set of Stages. It's equally viable to have 12 _completely parallel_ sets of Stages. Admittedly, that gets cumbersome.

The way I would approach this, personally, is to use a set of Stages for each smaller, logical grouping of microservices. How many logical applications do these 12 microservices amount to? For the sake of example, let's say that it's four logical applications, each comprised of a back end, a UI, and database migrations. In such a situation, I might opt for four completely parallel sets of Stages.

**Comment by ddeath** [comment]
@krancour but lets say you have those 12 microservices and you have DEV, STG, and PROD env which is shared between all of them.

If you group those microservices lets say to 4 groups how will you name the stages? Dev_1, Dev_2, Dev_3, Dev_4? I mean the stage represent the same env but we can have same name as it would conflict in k8s 😞

**Comment by krancour** [comment]
@ddeath I don't understand your question, especially as it relates to this issue. Can you please open a new question or issue and provide more detail in the question? We'd be happy to help.
