### ISSUE TITLE
Artifact details are truncated in freight details panel

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#2368]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

The issue is a follow-up for https://github.com/akuity/kargo/issues/2045. The freight details page now contains the container image name. This is great but image name is truncated so it is still difficult to see what is deployed without copying value from tooltip

# Screenshots

<img width="691" alt="image" src="https://github.com/user-attachments/assets/9c437e5f-61c1-4a28-8d67-3eb20a7d69fe">

# Steps to Reproduce

* Ensure Kargo project has a frieght with a long image name
* Click on frieght details page

# Version

```
v0.7.0
```

**Comment by rbreeze** [comment]
@alexmt This was fixed in 0.8 in https://github.com/akuity/kargo/pull/2277 (see the screenshot below as well), so going to close this issue. Feel free to reopen if it's not fixed in the way you expected.

<img width="617" alt="Screenshot 2024-08-05 at 08 15 36" src="https://github.com/user-attachments/assets/d4b4e48f-7bb9-41fc-9eb0-5334448fafad">
