### ISSUE TITLE
Freight Timeline horizontal scroll not obvious/easy

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2385]
# Proposed Feature

The freight timeline may long. And so color indicators may stop showing up. e.g. in below example, the purple stages are not shown in the timeline:

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/6fdb03fd-d42b-44d5-8be6-5c08cfd280c8">

The freight timeline is actually scrollable and users are expected to scroll to the right to see their old freight. But there is no easy way to scroll horizontally, unless:
* user uses trackpad to scroll
* user holds shift while scrolling with their mouse wheel
* user's mouse has a horizontal scrolling wheel

# Motivation

I wanted to view the purple stages, but was not able to until I learned the trick about holding shift. 

# Suggested Implementation

@rbreeze suggested to making the scrollbar visible so that users can use drag and scroll.

**Comment by jessesuen** [comment]
https://github.com/akuity/kargo/issues/2386 could also address the issue if there is too much freight.

**Comment by rbreeze** [comment]
@jessesuen I'm not sure there's a way to accomplish this when users have the default "Show scrollbars = Automatically" setting enabled on a Mac. From the browser's perspective, the scrollbar is "always" there, but it's hidden because of the OS setting and there doesn't seem to be a way to override this via the browser.

When I set scrollbars to "Always",
![CleanShot 2024-08-06 at 14 09 51@2x](https://github.com/user-attachments/assets/cf4d8ffd-048f-4e07-a7bc-031843e28114)

this is how it appears:
![CleanShot 2024-08-06 at 14 07 49@2x](https://github.com/user-attachments/assets/ee2b166c-4947-4b17-8d57-f9b3fb3d2133)

Perhaps another way to always indicate scrollability is to add a small icon or message to the bottom right of the freight timeline?

**Comment by jessesuen** [comment]
Discussed with Remington and I suggested we add left/right arrow buttons in UI that would allow the freight timeline to scroll.
