### ISSUE TITLE
Reassign Stage Colors doesn't do anything

### ISSUE THREAD

**Issue by NathanHRich** [akuity/kargo#2501]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Clicking the "Reassign Stage Colors" button in a project doesn't do anything, just refreshes the page. There aren't any console or network errors, which leads me to believe this is expected behavior? I've searched the docs and GitHub issues for details on if this is expected behavior but have come up dry.

I'd appreciate the ability to customize the colors of my stages either in the UI or in YAML. To that end, maybe this is just a feature request.

# Steps to Reproduce

1. Open any project
2. Click the "Reassign Stage Colors" button

# Version

```
v0.8.7
```

**Comment by krancour** [comment]
That button just re-runs the color assignment algorithm. I'll admit to having wondered, at times, why we have it. In practice, however, it's been a useful way to fix the colors when, inexplicably, everything turns black or two nodes in the DAG are somehow using the same color. i.e. It has always felt to me that it was a stop-gap measure until we figure out the source of our color bugs, which I presume to be something funky in the library we're using to draw the DAG. I'll let @rbreeze weigh in on whether he intended for that to be something more than a temporary workaround.

**Comment by NathanHRich** [comment]
Yeah, that's what I suspected after not seeing any errors after clicking that button. It's working "as intended". The intention just doesn't match the expectation of being able to actual reassign colors as the name suggests. Maybe "Refresh Chart Colors" or something would make more sense. 

Feel free to convert this to a feature request for the ability to reassign the colors of stages.

**Comment by rbreeze** [comment]
@NathanHRich The button actually doesn't just refresh the page, it clears the local storage object which maps each Stage to a specific color. The idea behind it is to regenerate the color mapping if you add a new Stage, for example. It's also come in handy between version upgrades when we've changed the coloring algorithm.

@krancour In a way it's a stop gap, and in theory we could automate detection of new Stages, but in practice I think it's useful in enough situations that it's worth having. Maybe it could be more hidden to avoid confusion.

@NathanHRich You can actually already assign specific colors to specific Stages by using the annotation `kargo.akuity.io/color` on the Stage object.

I updated the label to hopefully help clarify in this commit (since it's small IMO not worth its own PR): https://github.com/akuity/kargo/pull/2550/commits/9df49d18fe1093756f8f653fddd75cc792a9a1b3
