### ISSUE TITLE
docs: Show Expected Output for Commands

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#2504]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.

# Proposed Feature

It would be helpful if the `expected output` of certain commands were included in the documentation or comments. 
For example, after running the command `make hack-kind-up`, the user might see something like:

```
Release "argo-rollouts" has been upgraded. Happy Helming!
```
or
```
> k get no
kargo-dev-cluster-control-plane   Ready 
```
# Motivation

helps users verify that they have executed commands correctly. 
reduces confusion when users are unsure whether the command worked as intended.

# Suggested Implementation

Mention `expected output` for commands in [documentation](https://kargo.akuity.io/contributor-guide/hacking-on-kargo) wherever applicable.

**Comment by nitishfy** [comment]
IMO, the output might differ for some users. Instead of pointing the correct output, a better way is to provided a fix to the possible errors that can be encountered during the implementation of specific steps. We should try to keep the kargo docs as simple as possible. We can take inspiration from how the [Argo Docs](https://argo-cd.readthedocs.io/en/stable/developer-guide/running-locally/) have been written.

**Comment by krancour** [comment]
Let's show output where it is helpful to do so.

There are many cases where it is not, including ones (like `helm install` commands) where the output is verbose and of limited value.

With that being said, I think I take it for granted that it's _obvious_ when a command succeeds or fails and the docs might currently reflect that. It is obvious to me, in large part, because I have my shell prompts configured to give visual cues as to the success or failure of the previous command. Obviously, not everyone has that...

So what might be helpful, in some cases, is to provide commands that make it easier to validate the outcome of previous ones.

For instance, for a contributor running `make hack-install-prereqs`, they should be able to run `kubectl get deployments -n cert-manager`, `kubectl get deployments -n argocd`, and `kubectl get deployments -n argo-rollouts` and in all cases see 1/1 replicas ready, up to date, and available.

Provided we don't go overboard, I'd be very supportive of these sort of commands and example output that assert success in critical places.

**Comment by krancour** [comment]
As I think this is _primarily_ applicable to the quickstart, which is trending toward being more UI-centric, I think this issue is much less relevant now. Closing.
