### ISSUE TITLE
bug: comparison error in health check

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2593]
I'm seeing many directive-based promotion workflows working e2e now, but I am frequently observing Stages who reported as unhealthy due to an underlying Application having a "comparison error."

The funny thing is that simply refreshing the Stage will re-evaluate health and unstick things.

Since it's the same health check logic running when the comparison error is found and again when it isn't, my assumption is that there really _is_ a comparison error that is cleared in the time between the two checks...

But when I used the legacy promotion mechanisms, I don't encounter this.

I haven't dug into the relevant bits of code yet, but this sounds very much to me as if we were, possibly, promptly re-queueing Stages on failed health if the Stage uses legacy promotion mechanisms and perhaps are _not_ doing that if using promotion steps instead.

@hiddeco is there any chance you'd be willing to dig into this one?

I don't think this needs to block us from cutting a v0.9.0-rc.1, as it's easy enough to work around this issue in the near-term by refreshing a Stage.

**Comment by hiddeco** [comment]
The cause of this is very likely the indexer which knows what Stage is responsible for what Application not having been updated to incorporate the new logic.

This currently relies on the Stage having promotion mechanisms defined, which is no longer true when working with promotion directives.

As we trying to detach these kind of magic relationships as much as possible, we would prefer becoming aware of this without treating one or more directives as "special" (by interpreting their configuration). We need to find another way to establish this relationship.

Kent pointed out that Applications must be annotated with `kargo.akuity.io/authorized-stage: <project>:<stage>`, which we can likely use in an inversed manner (Application -> Stage, instead of the other way around) to know what reconciliation we should request when a transition occurs in the Application status.

**Comment by krancour** [comment]
Thanks for so quickly finding the root cause.
