### ISSUE TITLE
Ability to update promotion and freight status for similar stages in different projects

### ISSUE THREAD

**Issue by ed-boykin** [akuity/kargo#2703]
# Proposed Feature
The ability have a stage in one project be updated with freight and promotion information from a stage in another project. 

For our Kargo implementation we have a separate project for each microservice we deploy. There are about 25 so far and that number is growing.  For our releases we create a project with some number of these service to be released. The idea being, if we have 10 services a release, we dont want to require going to 10 different kargo projects to deploy each one.  

However, when we do this, the individual projects do not reflect the promotions from the 'combined' project.

If possible, someway to link freight, stages, and projects such that an update in one would update the other(s). This would work both ways. I wouldnt expect this to occur without some explicit configuration to create the link.

**Comment by krancour** [comment]
It was by design that related things are meant to be in the _same_ Project. Projects are basically namespaces. In fact, behind that scenes, they _are_ namespaces. The requested change seems as if it would fundamentally break everything. I struggle with how we could even (efficiently) assemble and render the DAG for a pipeline that spans Projects.

**Comment by ed-boykin** [comment]
I understand what you mean, and I wondered about the namespace issue. It sounds like Ive implemented a bit of an anti-pattern in how I set things up and I should rethink some things. Perhaps a better setup on my end would remove my need for this request.  I'm good with closing this.
