### ISSUE TITLE
Image history randomly sorted. Changes on every refresh

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2767]
# Description

The image history is randomly listed and changes on every refresh:

https://github.com/user-attachments/assets/9a1f8290-bd35-486a-92a5-4225c7d6b0a3

We should sort by semantic version if we detect that they are semvers (we can just look at the first one to determine this), and then fall back to lexographical if it's not a semvers. 

# Version

```
v0.9.0
```

**Comment by krancour** [comment]
The data structure that drives this is composed on the back end since #2389. I looked at this briefly today, hoping it would be a quick fix, but it's quite complex as it turns out, and I believe the structure of this data will have to be revised (to be less map-centric and more list-centric). @Marvin9 and I will have to tag-team this so the front-end and back-end agree on the new data structure.

**Comment by krancour** [comment]
iirc, @rbreeze had said that UI performance improved a lot by offloading this to the back end.

**Comment by Marvin9** [comment]
That makes sense. The sorting is already fixed from the UI itself so closing it.
