### ISSUE TITLE
Promotions stuck Pending in v1.0.0

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2795]
# Description

After upgrading from v0.9 to v1.0, promotions are stuck Pending

# Screenshots

![image](https://github.com/user-attachments/assets/73a5a1ca-7e20-4c99-82ea-bb3b72ca5f89)

# Steps to Reproduce

# Version

```
v1.0.0
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by michaelasper** [comment]
Similar issue on our side; i've found kicking the promotion again and aborting the old one lets it start instantly

**Comment by wmiller112** [comment]
I seem to be hitting this on 1.0.1 as well. After successful verification in previous stage, promotion created in stage that has no verification and gets stuck pending

**Comment by wmiller112** [comment]
Seem to be experiencing this periodically on versions after this fix (tested 1.0.1 and 1.0.3). Promotion stays pending in stage and have to abort and manually promote the freight a second time.

**Comment by krancour** [comment]
@wmiller112 does the Stage(s) in question have verification processes defined?

I am also curious whether it is possible your Stages (and underlying Apps) were Progressing when you observed this?

**Comment by wmiller112** [comment]
The stage does not have verification defined. It is progressing sometimes, as the managed apps auto scale pretty aggressively, and the stage manages ~20 apps. So even once they become healthy, the stage frequently goes back to progressing.

**Comment by krancour** [comment]
I believe you're seeing it work at intended at this point, believe it or not.

Since you haven't defined a verification process, the criteria for verification is the Stage reaching a healthy state.

If the Stage is Progressing, it's _trying to reach_ a healthy State as is at least one of your underlying Applications. Since this is basically your verification, the next Promotion will not interrupt it. When the Stage reaches a healthy or unhealthy state, the next Promotion will run.

It seems like your Stage is pretty huge. I can understand Progressing taking a while and I would expect that to then block the next Promo for some time...

How certain are you that Promos are really stuck and not just being handled at a snail's pace due to the size and complexity of your Stages?

**Comment by wmiller112** [comment]
I see, so sounds like a very basic verification would satisfy the health of previous promotion and keep the periodically "progressing" apps from causing delays. Its interesting that cancelling the auto generated promotion and triggering one manually seems to bypass that.

**Comment by krancour** [comment]
> I see, so sounds like a very basic verification would satisfy the health of previous promotion and keep the periodically "progressing"

> Since you haven't defined a verification process, the criteria for verification is the Stage reaching a healthy state.

Yes. Since it seems we didn't account for the possibility of things returning to a Progressing state after reaching a healthy state.

Note that your verification won't _kick off_ until you reach a healthy state (but it won't be disrupted by a return to a Progressing state).

fwiw, this whole section of code is probably the trickiest in all of Kargo and we're actively working on refactoring it to make it easier to comprehend and, hopefully, therefore easier to accommodate edge cases as they are discovered.
