### ISSUE TITLE
docs: update go/crd docs with semantic version info

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#2833]
ref: https://github.com/akuity/kargo/pull/2521#discussion_r1814010960

**Comment by krancour** [comment]
> We can move this to be inline in the Go/CRD docs.

It turns out it is already mentioned here:

https://github.com/akuity/kargo/blob/1a7ab783e48cd04be0343bf4e1ff689090352fc3/api/v1alpha1/warehouse_types.go#L241-L253

(Although the comment about referring to Image Updater documentation ought to be removed. That is leftover from a time when image selection functionality was borrowed from Image Updater. That is no longer the case.)

This is another spot where semver constraints are mentioned -- this time for commit selection:

https://github.com/akuity/kargo/blob/1a7ab783e48cd04be0343bf4e1ff689090352fc3/api/v1alpha1/warehouse_types.go#L137-L146

Run codegen after updating these comments.

**Comment by krancour** [comment]
@fykaa you could consider addressing #2880 in tandem with this as they are very closely related.
