### ISSUE TITLE
Add feature to add Tag to image

### ISSUE THREAD

**Issue by stephaneetje** [akuity/kargo#2892]
I would love to have the ability to add a tag to an image.
My workflow:
- I deploy every image (v.x.x-$SHORTSHA) on integration environment
- When promoted from integ, i would like to add a Tag without the SHORTSHA (to be deployed on production envs)

Am i doing it the wrong way ?

**Comment by krancour** [comment]
> Am i doing it the wrong way ?

We don't exactly _encourage_ it, but I'd stop short of saying it's wrong.

The reason we don't really encourage this is it feels antithetical to what Kargo aims to do. Your intent is to promote specific versions of artifacts through a series of environments. If the identifiers used for those versioned artifacts _change_ somewhere along the line, it complicates things quite a bit.

Support for an expression language is coming in v1.1.0. Custom/third-party promotion steps are coming in v1.3.0. I think between those two features, you'd be able to create a custom promotion step that derives a new tag name, using EL, from the original tag name and pushes it. The original tag name would remain unchanged in the Freight that is moving through your pipelines. Again, using EL, you could make Stages downstream from the point where images are retagged aware of the new tag name.

This seems about the best that could be done because _Freight are immutable by design_.
