### ISSUE TITLE
Kargo app updater doesn't clear the `app.Status.OperationState` when setting application operation, leading to inconsistencies during ArgoCD sync

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [akuity/kargo#2985]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Kargo app updater doesn't clear the `app.Status.OperationState` when setting application operation, see https://github.com/akuity/kargo/blob/cc293f0bd128943e097d9ae76ea69469b7a1c462/internal/directives/argocd_updater.go#L476-L528. But ArgoCD does that in its `SetAppOperation` https://github.com/argoproj/argo-cd/blob/32cc6638f78e15652c24eb2cd6403e6e7ec26ab0/util/argo/argo.go#L820. This seems to result in ArgoCD UI showing a new sync operation started with details of the old sync for a few seconds, as operation and status are not consistent between each other. There might be deeper consequences like app remaining out of sync.

# Screenshots

![Screenshot 2024-11-22 at 5 45 17 PM](https://github.com/user-attachments/assets/a843a752-f139-4e4d-a763-6b41a7252dd0)
![Screenshot 2024-11-22 at 5 46 12 PM](https://github.com/user-attachments/assets/4e6783e4-2b72-4abf-9d3a-fa6d7982cf51)
![Screenshot 2024-11-22 at 5 46 15 PM](https://github.com/user-attachments/assets/73c7eabb-bc47-4b94-aa86-73a819b0e34c)
Courtesy of @stephaneetje.

# Steps to Reproduce

Change the tag in helm values and trigger an update through Kargo.

# Version

Not provided

# Logs

Not provided

**Comment by andrii-korotkov-verkada** [comment]
See the discussion from this comment https://github.com/akuity/kargo/issues/2968#issuecomment-2494917735 and below for more context.

**Comment by krancour** [comment]
I did mention before in the other thread that this is kind of a no-no. A resource's Status is meant to be manipulated by the controller responsible for it and not by others.

**Comment by andrii-korotkov-verkada** [comment]
But you manipulate the operation field with bypassing server APIs ;) What's the substantial difference making it a no-no and operation field updates yes? However, I'll check if it's possible to clear the status field by the controller if it's about a completed operation finished before the current sync started.

**Comment by krancour** [comment]
> But you manipulate the operation field with bypassing server APIs ;) What's the substantial difference making it a no-no and operation field updates yes?

This is Kubernetes 101. Status is a special field. It is one of only a handful of fields that Kubernetes regards as a "subresource" and treats differently. What is different about a subresource is that the endpoints for creating/updating a resource ignore changes its subresources. Instead, the subresources get their own endpoints.

RBAC is an area where you can see this on full display. Permission to update a resource kind X _doesn't_ automatically come with permission to update X.status. That has to be requested separately. (Since, as I said -- it's a separate endpoint.) i.e. You would need to grant permissions on resource kind `x/status`. In practice, you probably see this pretty rarely though, because the only principals who usually get such permissions are the controllers responsible for those resources.

So if you were to look at the permissions of the Kargo controller, for instance, in addition to resource kinds like `stages` and `promotions`, you'd also find `stages/status` and `promotions/status`. For the Argo CD Application controller, in addition to `applications`, you'd see `applications/status`.

The reason you don't see this more often is precisely because, by convention, status subresources aren't meant to be manipulated by third parties. By convention, that field is _exclusively_ for the controller responsible for the resource to reflect the observed state of the world. No one else should be touching it.

**Comment by andrii-korotkov-verkada** [comment]
Thanks for the explanation. I'll look into whether it's possible to handle better at ArgoCD side. Maybe it's just as simple as reset status field on app update if it became obsolete.

**Comment by andrii-korotkov-verkada** [comment]
Trying this https://github.com/argoproj/argo-cd/pull/20915

**Comment by andrii-korotkov-verkada** [comment]
I've made it ready for review, working for both live environment and tests. Hope ArgoCD maintainers accept it.

**Comment by krancour** [comment]
Closing this as I believe there's agreement that no one but Argo CD should update Application _status_ and https://github.com/argoproj/argo-cd/pull/20915 seems as if it may, pending review, address the reported issue on the Argo CD end.

**Comment by jessesuen** [comment]
After further internal discussion, we conceded that Kargo can clear `.status.operationState` (at least temporarily), since it's unclear if & when Argo CD will change it's behavior.

So `.status.operationState` will be cleared the same time the operation is set. Implemented in https://github.com/akuity/kargo/pull/3069 and will be in v1.1
