### ISSUE TITLE
PR Labels

### ISSUE THREAD

**Issue by mmclane** [akuity/kargo#3002]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

kargo v1.0.3

# Proposed Feature
It would be really great if we could set PR labels via the git-open-pr step.  

# Motivation
We like to use them to filter our PRs in github and it would be nice if we didn't have to do this after the PR is created.
Additionally, one could have a github action triggered based on the label being added and the value.  While I don't have an immediate use case for this, I could see how I might use it.

# Suggested Implementation

The git-open-pr promotion step could have a configuration item that is Labels that is of type list of strings.  Each item in the list is added as a label after the PR is opened.  

It would be worth noting that the labels have to pre-exist in your github repo for the workflow to add the label, but that would be on the creator of the workflow to insure.

**Comment by krancour** [comment]
PR labels seem like a sensible request and one that's easy enough to implement.

Same for title. Setting a custom title didn't make sense prior to expression language support because all your PR titles from a given Stage's Promotions would have been static/identical. With expressions, it should be possible to dynamically build a more meaningful title. If you don't mind, please open a separate issue for that.

**Comment by muenchdo** [comment]
I'd be interested in taking a stab at this one 🙂
