### ISSUE TITLE
Using `envconfig` for parsing environment variables

### ISSUE THREAD

**Issue by devholic** [akuity/kargo#438]
https://github.com/akuity/kargo/pull/435#discussion_r1237752172

**Comment by krancour** [comment]
I've used this a lot in the past and moved away from it over time for reasons I can no longer remember.

I'm willing to head in this direction and then change course only if valid reasons resurface.

**Comment by krancour** [comment]
I hope no one will mind me self-assigning this. I am somewhat in need of a chore-type PR to zen out on this morning.

**Comment by krancour** [comment]
@devholic @rbreeze 

I remembered why I once moved away from using envconfig.

This is relatively academic, but I didn't like that the struct tags couple config struct fields _so directly_ to env vars.

If you consider a given config struct possibly being used in a variety of different contexts, you may sometimes want to bind the fields to _different_ env vars. To accommodate those cases, I adopted a habit of letting main programs define the binding of env vars to config struct fields.

Academic as that argument is... I'm content to dismiss it and move forward with this since it's less code to maintain.
