### ISSUE TITLE
Advance function that can better support production rollouts

### ISSUE THREAD

**Issue by yangtian9999** [akuity/kargo#443]
Hi Akuity Team,

There is an Argo CD server that manages deployments for blue and green Kubernetes clusters. The blue and green clusters are for production rollouts. Under certain conditions and requirements, we need to disable/enable specific setting of clusters for production rollout purposes.

For example, currently the blue cluster is serving live production traffic. The green cluster should have all business application network policies disabled to ensure real traffic cannot reach the green side. When performing a rollout, the green cluster becomes the production cluster. The green cluster's network policies should then be enabled, and the blue cluster's policies should be disabled.

Also, in the same scenario, when the blue cluster is serving production, the green cluster will maintain minimal replicas for the business application deployment. After rollouts, the green one's replicas should be set to the normal number which is bigger than the minimal, and the blue one's should be set to minmal.

During this rollout process, no one is allowed to commit anything to the Git repos to update such changes. Is there a better tool or solution to implement this?

If need any more additional explanation, pls let me know, thanks.

**Comment by krancour** [comment]
Hi @yangtian9999 thanks for the interest in our project!

In my experience, it's somewhat unusual to do blue/green deployments using entirely different clusters. If you were doing it within a single cluster, there's a project called Argo CD Rollouts which provides a drop-in replacement for the Kubernetes `Deployment` type and implements more sophisticated deployment patterns, such as blue/green and canary. And this works seamlessly with Argo CD already. If you're additionally using Kargo, everything still just works.

If you aren't already familiar with that project, I would suggest checking it out.

If, on the other hand, you were familiar with this option and had to reject it because something else has forced you down the two cluster route, it may be helpful to you that we are planning to eventually provide hooks that allow arbitrary pre and post-promotion logic to be executed. It's very hard to say at the moment how soon we're going to get to that.
