### ISSUE TITLE
the governance action we set up recently fails every time

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#473]
I haven't had any time yet to look into what is wrong.

**Comment by kencochrane** [comment]
This gave an HTTP error because it couldn't download the governance.yml file; I'm not sure why since it is there. Originally it had an issue because the file was named wrong, so I renamed it. That still didn't fix it, so I added the location to the file to be sure, even though it was in the same place as the default location. It still gave an error. 


```
Run BirthdayResearch/oss-governance-bot@v3
  with:
    config-path: .github/governance.yml
    github-token: ***
github-client: getBotUserId
ignore: ignore bot - type:User - login:<username>
Error: HttpError: Not Found
Error: HttpError: Not Found
```

Here is the config file, I'm not sure why it can't find it. https://github.com/akuity/kargo/blob/main/.github/governance.yml

Here is the code in the github action that is getting the config file, it looks fine to me. 

https://github.com/BirthdayResearch/oss-governance-bot/blob/main/src/config.ts#L159-L174

I merged the PR to see if that helps with future PRs. If it does, we are good, if not, we will need to re-open
