### ISSUE TITLE
Freight CRD

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#631]
While working on the [QueryFreight API](https://github.com/akuity/kargo/pull/629), it made me realize that freight is just metadata that we are constantly carrying over from Stage to Stage. And so the implementation of QueryFreight, is a bit awkward. It iterates all Stages first to collect all freight in each Stage. Then it does a bunch of deduplication code to prevent duplicates from returning. Which btw, is not fool-proof: there's nothing to stop someone from editing their stage's freight contents and messing up the result. Principally, we consider freight as something immutable. 

For this reason, I started to wonder if we should start treating freights as a first-class resource in Kargo with its own CRD.

Here are some of the benefits I see:
1. Easier to query. The QueryFreight API would be improved to just deal with the CRs.
2. Freight would become more immutable. We would treat the Freight CR as something that should only ever be created and deleted (for GC), but never updated or patched. We could use kubernetes RBAC to ensure this is the case.
3. Lifecycle of Freight would be decoupled from lifecycle of stages. In other words, we could recreate a Stage without losing Freight.
4. We would reduce the amount of duplicate metadata in the Stage status, since details of the freight (e.g. image tag) would be kept in the CR. 
5. We could keep more freight history. Currently, we limit to 10 freight per Stage. But by putting it into a different CR, we could keep an indefinite amount of freight.
6. When it is a kubernetes object, we could be more creative on how to take advantage of that property. For example, we could:
    * use ownership references to indicate the freight is still in use and prevent garbage collection.
    * label and index freights with the way we intend to query against them
    * have other things besides Stages, deal with and reference Freight

**Comment by krancour** [comment]
Let's have this be the main topic of discussion at next week's meeting.

**Comment by jessesuen** [comment]
Sure, though I don't want to get too distracted with the proposal since it's not blocking any functionality. And I'm also not suggesting we do this for v0.1.0.

**Comment by krancour** [comment]
Oh. Thank you for clarifying.

**Comment by krancour** [comment]
Off today, but had some thoughts about this that I wanted to capture for future discussion.

I'm not 100% sure of this, but the thought has crossed my mind -- what if Freight is a CRD, _but Promotion is not_?

I'm trying to look at this through a pets vs cattle lens. _Freights seem to be named things that we care about. i.e. Pets._ Promotions _only_ seem to be the time a Stage spends transitioning between two Freights. I don't think they're noteworthy over the long term. i.e. Cattle.

I think this could also move us closer to the Kubernetes ideal in terms of the declarative vs imperative dichotomy.

So image:

* Stage reconciler for a "zero stage" (subscribed directly to repos) finds new Freight, just like it does today, but instead of making it "available" within the Stage's status, it just creates a CR to represent the new Freight.

* Stage _spec_ specifies the desired Freight. (We don't do this today.)

* Stage status doesn't need to directly track what freights are available, but it can still maintain history of what Freights have moved through the Stage.

* Freight reconciler tracks qualification of each Freight across all stages in Freight status. i.e. Freight controller is constantly asking, "In what stages has this Freight becomes fully healthy?" Any time a Freight qualifies for the first time in a new Stage, that new qualification makes it available to Stages immediately downstream from that one. For Stages where auto-promotion is enabled, promotion is then effected by the Freight reconciler updating the desired freight in the

* Manual promotion also is just a matter of updating Stage spec with a reference to the desired Freight.

Just some ideas for later.

fwiw, I also estimate that effort-wise, this isn't too much of a pivot.

**Comment by krancour** [comment]
In terms of RBAC, we keep everything as it is today, using the "dolphin verb" promote to denote special ability to mutate the desired Freight in a given Stage spec. That will then be enforced with a validating webhook that monitors changes to that field.

**Comment by jessesuen** [comment]
> but instead of making it "available" within the Stage's status, it just creates a CR to represent the new Freight.
> Stage status doesn't need to directly track what freights are available, but it can still maintain history of what Freights have moved through the Stage.

Yes. This is exactly what I am thinking.

> what if Freight is a CRD, but Promotion is not?
> Stage spec specifies the desired Freight
> Manual promotion also is just a matter of updating Stage spec with a reference to the desired Freight.

This is an interesting proposal. I would want to know how pull request promotion would work which is imperative by nature. I do think having a Promotion object lying around in the system with a record of how it failed, links to the pull request, etc... is still useful to keep around. I also think that Promotions are simple today, but may be user-defined and will be complex tomorrow.

> using the "dolphin verb" promote to denote special ability to mutate the desired Freight in a given Stage spec. 

Yes, one of the original reasons for a Promotion CRD was to have separate RBAC for CRUD on stage vs. promoting. e.g. `kubectl create` a promotion object. We've since learned that dolphin verbs can support this without an actual CRD.

**Comment by krancour** [comment]
> I would want to know how pull request promotion would work which is imperative by nature. I do think having a Promotion object lying around in the system with a record of how it failed, links to the pull request, etc... is still useful to keep around.

I wouldn't want to lose any of that either. I would put in in the Freight's status, keyed by Stage name.

"Did this Freight qualify for Stage x? Yes? Great! No? Here's structured details on what went wrong."

**Comment by jessesuen** [comment]
I wanted to capture some more thoughts I just had that a Freight CRD will enable.

Today, a zero environment can subscribe to one or more of:
* image repos
* git repos
* helm repos

When thinking about this, these things are just just mechanisms that produce freight.

I wonder if we could change our mentality a bit, and instead of Stages subscribing to these specialized implementations (image, git, helm), Stages could be subscribed to a stream of Freight, without caring about how they were produced since it was done elsewhere.

This would result in some changes:
* We would need a way for users to define something that *produces* Freight (e.g. FreightFactory)
* Stages would no longer have syntax to subscribe to image/git/helm explicitly but rather a selector of freight. Though, I still like the syntax of subscribing to upstream Stages.

The benefits I see are a decoupling the Stage reconciler's responsibility for understanding how to produce freight (clone git, etc...) and focus more on other things like verification, health, and initiating promotions.

**Comment by krancour** [comment]
Agree with all of that!

**Comment by krancour** [comment]
In terms of visualization, I would still want to see all the repos that supply the freight on the far left of the DAG.

**Comment by tal-hason** [comment]
> In terms of visualization, I would still want to see all the repos that supply the freight on the far left of the DAG.

something like this:
![image](https://github.com/akuity/kargo/assets/97454240/81c24294-6076-4a43-8007-740c82d0187a)
