### ISSUE TITLE
Docs are continuously refreshed from `main` causing the guides to break

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#695]
As discussed in [#679](https://github.com/akuity/kargo/issues/679#issuecomment-1711784940), because the docs are continuously refreshed from `main`, so it tends to represent features and functionality that are not currently released. This results in the quickstart guide (and likely other sections) breaking.

Instead, the live docs page (`kargo.akuity.io`) should be updated when a new release is cut. A second page `kargo.preview.akuity.io`, should be used to reflect what is currently on `main`.

**Comment by krancour** [comment]
I will set this up, but probably not before EOY.

**Comment by krancour** [comment]
This turned out to simply be a matter of technique and we successfully applied it for v0.3.0 where we had a number of doc changes accumulate in the `release-0.3` branch. Netlify was configured to continuously update a preview of those docs. I think we've got a good enough hold on how to do this now that we can just close this issue.
