### ISSUE TITLE
Manually input freight

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#761]
I have predefined images in a container repository. Currently, the only way these images can be detected and entered as Freight by kargo, is if we subscribed to that container repository for a stage before those images were created.

That is all well and good for an app developer deploying their service continuously in a SaaS. But in my use case, the images I care about promoting, were developed by someone else and existed long before I started using Kargo. So more of an operator use case than an app developer.

I would like the ability to manually input freight with images. Even better, is if we had an API/UI feature that presented container images (not yet been created as freight), and allowed me to convert them as freight.

The [Freight CRD](https://github.com/akuity/kargo/issues/631) would probably help here

**Comment by krancour** [comment]
I agree we need this capability, but if you have an immediate need to do something like this, I do think, it can be done today if the third-party image is semvered.

**Comment by jessesuen** [comment]
This use case was brought up by @wanghong230 today. When connecting a git/container repository to a warehouse, we only fetch the most recent freight. He proposed that some last N freight be populated.

Though I think a manual ability would be sufficient to suit this use case.

**Comment by krancour** [comment]
> He proposed that some last N freight be populated/backfilled.

The tricky thing about that is that a piece of Freight is a _combination_ of other artifacts.

Say you fetch the last n imagess and the last m commits, then there are n * m different combinations of those and some number of them are probably invalid. i.e. HEAD~4 might be completely incompatible with the latest image.

> Though I think a manual ability would be sufficient to suit this use case.

I think this is the only reasonable way to reach back in time to pull something arbitrarily old into the pipeline.

**Comment by krancour** [comment]
This plays into #1680 and the new idea of a "freight lab."

**Comment by Brightside56** [comment]
> This plays into https://github.com/akuity/kargo/issues/1680 and the new idea of a "freight lab."
And this helps to resolve my issue with many artifacts for components of single microservice

**Comment by hiddeco** [comment]
We discussed this during an offline meeting today and concluded there that to make this work nicely and help address the "freight lab" idea. It should be possible for a user to have an overview of artifacts that are not part of a Freight but are available to a subscription of a Warehouse.

While it was opted there that we potentially could utilize Redis for this as a caching backend, I also briefly explored the idea of running a Kubernetes API extension server to _not_ have to deal with another side dependency we would have to protect and/or invent authentication mechanisms for.

This may all be too complex, as we already have a key/value store at hand (etcd) and the desire appears to only display a selective `n` of artifacts for a subscription before or outside the selection strategy of the current Freight.

Given this, @krancour and I have started to wonder if we can not simply keep track of the last `n` of artifacts available to a subscription in the Status of a Warehouse, which already is reconciled where it needs to be (e.g. on a user cluster).

Taking container images as an example, this could be as simple as:

```yaml
status:
  latestArtifacts:
    images:
      ghcr.io/akuity/guestbook:
      - tag: v0.0.4
        digest: 5b95870901f3878a2694ed941ce3083533dfba7648d47181901cfd8ac04f4d08
        created: 2006-01-02T15:04:05.999999999Z07:00
      - tag: v0.0.3
        digest: aadc1655396077ee1074274f52b7938797ad9e2903337be61e346ac70621bda8
        created: 2006-01-02T15:04:05.999999999Z07:00
```

The limitation would be the maximum size Kubernetes and etcd can cope with. But with 265 bytes per list item, this could – depending on our desire of maximum `n` and the number of subscriptions – not be a realistic issue.

**Comment by jessesuen** [comment]
> if we can not simply keep track of the last n of artifacts available to a subscription in the Status of a Warehouse

I like this proposal. It doesn't add the complexity that I was concerned with for some of the other approaches, and I agree that realistically we will likely not hit the etcd size limitations. Great idea!

**Comment by hiddeco** [comment]
When writing the proposal yesterday, I had not extensively looked at how Kargo does image selection, in addition to forgetting about the finer details of OCI image tags which I have historically run into multiple times before.

At present, Kargo selects the targets for a subscription using [`Selector` implementations](https://github.com/akuity/kargo/blob/cbc96eaf5d627e60325926edff889e78cc72bc74/internal/image/selector.go), which will query the OCI registry based on their specific needs. For example, a [SemVer selector](https://github.com/akuity/kargo/blob/cbc96eaf5d627e60325926edff889e78cc72bc74/internal/image/semver_selector.go) will only iterate over the available list of tags for an image to parse them as SemVers — while a ["newest build" selector](https://github.com/akuity/kargo/blob/cbc96eaf5d627e60325926edff889e78cc72bc74/internal/image/newest_build_selector.go) will also gather the additional metadata required to reason about the date and time the image was created at.

If we want to provide a list of _latest_ available images, any selector would need to gather the available tags and metadata for the subscription. Because of how content discovery was designed to work in the [OCI Distribution Spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md), which only provides a lexically ordered tag list without any digest or timestamps attached, this is extremely costly. As for the additional gathering of these bits of metadata, additional requests must be made to the registry.

While I can think of ways to make this as efficient as possible. For example, detaching the discovery bit from the selectors and periodically checking on them, backed by some (persistent?) cache. This has to be discussed, as it would be a major undertaking compared to the previous proposed solution.

However, this would not have to block manual Freight creation itself. Which could still be added in the UI using arbitrary user input, it would just be less intelligent.

**Comment by jessesuen** [comment]
I believe your original proposal should still work. We may have different expectations of the feature that is causing the complexity. Here is my view:

Today, Kargo already supports "skimming off the top" a single tag that follows the selection strategy of the Warehouse. In my view, this feature is just a variation of what we are currently doing, but differs in the following ways:

1. Instead of finding a _**single**_ most recent tag of the selector, we would need to find the N most recent.
2. Instead of immediately creating/permutating freight from what was discovered, we would store it into the status of the Warehouse, so that the user could choose to create freight from what was recorded.

This is what I **_do not_** expect out of the feature:
* Realtime browsing capability of what is in the registry, and for a user can navigate to any arbitrary point in time to select an tag. I think this is large technical challenge, as you pointed out to me, all image registries (quay, ghcr, dockerhub), create their own vendor-specific API layer to drive their UI and we cannot reasonably accommodate all vendor APIs. Similarly, we are handcuffed by what OCI is able to return in their standard.

That said, there is the desire & use case for users to explicitly select image tags that aren't in the N most recent. To address this, I propose we implement a separate feature, where a user can signal to a warehouse to import explicit tags (outside the N most recent), so that they populate into status, and then become selectable in the UI.

Here is how I propose the feature work:
1. a user creates a Warehouse _with automated freight creation disabled_. They do not want Freight to be generated with every image push. This Warehouse watches image repo `docker.io/guestbook`
2. When the warehouse is created, we immediately populate the 20 most recent tags of `docker.io/guestbook` into the status of the Warehouse. 
3. Unfortunately, the 20 most recent tags do not go back far enough for the user. They want something older.
4. Using some API, user can specify a time range, or semantic version range, or even a specific tag, for which they wanted to backfill tags the Warehouse status (outside the initially discovered 20)
5. At this point in time, the kargo controller would do the expensive work to discover the images in the requested range

From what I see, there times when it becomes expensive to discover tags becomes manageable:
1. when a warehouse first populates the 20 most recent
2. when the user manually requests a tag range or explicit tag
3. once every 3 minutes during normal reconciliation

**Comment by hiddeco** [comment]
I think this would introduce a way forward, but I do fear that "once every 3 minutes during normal reconciliation" could still cause problems for quite some real-world repositories when selecting by date. Assuming you have 1000 tags (and in my experience, this is a conservative number when developers push frequently and build for every commit), this would still result in about 2000 requests every 3 minutes.

However, this problem is not introduced by this feature itself and already exists for the current "pick latest automatically" behavior. Given this, I am happy to move forward with your suggestion and revise when we receive reports about performance issues.

**Comment by jessesuen** [comment]
>  Assuming you have 1000 tags, ... this would still result in about 2000 requests every 3 minutes.

I have a question about this statement, once we had populated the status for that tag, would there be a need to make additional requests for that tag? In other words, once we calculated the metadata for a tag once, do we ever need to revisit it again?

**Comment by krancour** [comment]
The fact that tags can, unfortunately, be mutable, necessitates _at least_ querying to find the digest the tag _currently_ points to. Once we have that, the information associated with that digest is typically found in the cache.

Also, for most strategies, we don't go after all this metadata up front. We select _a_ tag and then go after its metadata. iirc, it is only the "newest" build strategy that requires extensive metadata up front _before_ making a selection.

I do think this still looks pretty nasty when the cache isn't primed.

I also think selecting the "n latest" commits that the warehouse would have selected from a git repo also looks pretty nasty. Since the introduction of path-based filters (good for monorepos) not every commit is a commit of interest. We don't actually know how far back we need to go to find n commits of interest -- which means this could be quite chatty, initially, but with git history being substantially less mutable than an image repo, at least this isn't so bad on an on-going basis. It's picking the _initial_ n that is hard and it gets easier after that.

**Comment by krancour** [comment]
I don't feel comfortable assuming only latest is mutable. Even popular official images like Nginx have proven this to not be a safe assumption, unfortunately.

**Comment by hiddeco** [comment]
I discussed adding a CLI option with @krancour, and we were both of the opinion that it would very likely be too cumbersome ever to create a proper piece of Freight using the CLI, and folks are better off using `kargo apply -f` for this.

Given this, and with #1984. The backend part of this should be there, and it is all frontend work that remains.
