### ISSUE TITLE
Allow Stage reconciler to reconcile Stages during Promotions

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#774]
Currently, we have a restriction that Stage reconciler will not reconcile Stages while there is a running promotion. This restriction exists because both reconcilers modify Stage status. It's possible that we can remove this restriction by avoiding the concurrent updates.

Here's how it would work:
1. Promo reconciler will stop updating a Stage's `status.history`, `status.currentFreight`, `status.availableFreight` when the promotion is completed. 
2. Instead, promo reconciler will simply store details of the promoted freight in the Promo's status.
3. During stage reconciliation, if it notices the currentPromotion is completed, it would do the job of updating it's own `status.history`, `status.currentFreight`, `status.availableFreight` with freight from currentPromotion's status.

I think this will be cleaner and allow the Stage reconciler to do other things while promos are happening (e.g. detect argo cd health).

**Comment by krancour** [comment]
Agree with all of this, but also think the need for this may be reduced once Freight is a CRD because the Stage reconciler won't be in charge of subscriptions anymore.

**Comment by krancour** [comment]
Stage reconciliation still stops during a Promotion. The Promotion reconciler basically takes over for the lifetime of an active Promotion.

But I _think_ the main issue here may have been that Freight production was basically halted while a Promotion was in progress at the "zero Stage," but this has long since been resolved when Freight became their own CRD created a by a Warehouse that runs completely independently of the Stages and Promotions.

Tentatively closing this.
