### ISSUE TITLE
metadata/message about original *code* commit

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#78]
When we make commit messages, we should somehow include git message of the actual code change. This can avoid situations like the following (our current hacky way):

<img width="578" alt="image" src="https://user-images.githubusercontent.com/12677113/191316394-b50b6562-2fc2-4fae-b615-bcf3df61f2c8.png">

**Comment by highb** [comment]
At my org, I've implemented a github action called action-promote, that adds metadata to the promotion commit into our deployment repos. I do find this information useful because there are many places that images could be promoted from and being able to trace back to the code repo in an unambiguous way has come in helpful several times for me. As an example of the sort of info that I include, here's an anonymized commit description generated by my action.

---
  GITHUB_EVENT_NAME: push
  GITHUB_JOB: promote
  GITHUB_REF_URL: https://github.com/org/repo/tree/refs/heads/master
  GITHUB_REF: refs/heads/master
  GITHUB_REPOSITORY_URL: https://github.com/org/repo
  GITHUB_REPOSITORY: org/repo
  GITHUB_RUN_ID: 123456789
  GITHUB_RUN_NUMBER: 1234
  GITHUB_SHA_URL: https://github.com/org/repo/commit/59247d97e98b7b80086185ea8af39639fcc5ee9c
  GITHUB_SHA: 59247d97e98b7b80086185ea8af39639fcc5ee9c
  GITHUB_WORKFLOW_RUN_URL: https://github.com/org/repo/actions/runs/123456789
  IMAGES: dockerhuborg/my-service
  CHARTS:
  OVERLAYS: env/my-service/integration
  MANIFEST_JSON: {"env/zeus/zeus-service/integration":{"images":[{"name":"dockerhuborg/my-service","newName":"12345.dkr.ecr.us-west-2.amazonaws.com/dockerhuborg/my-service","newTag":"sha-59247d97e98b7b80086185ea8af39639fcc5ee9c"}]}}
---

Obviously, the GH workflow specific URL info isn't useful in Kargo but perhaps a link back to the Kargo event that started the promotion would be? I do think that having an integration with the underlying app code repo would be extremely helpful for devs to easily trace back to their code changes, regardless of if the image is tagged with a sha or SemVer.
