### ISSUE TITLE
Freights line combined of freights permutations from multiple subscriptions is questionable

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#832]
Currently, Kargo allows subscribing the `0` environment to Git and Image Registry. New commits and new images are used to produce a list of freights that users can promote using Kargo UI.

# Problem

IMHO, the typical workflow is different: 

* engineers keep making code changes and some automated process bump images in `env/dev` folder. 
* once code is more of less ready engineer manually change config to enable new feature
* attempts to promote new image + config to `env/stage`
* find bugs and more code changes
* attempts to promote new image + config to `env/stage` and then finally to `prod`.

The main difference is the list of "freights" is in Git only. I personally would not benefit from the ability to pick a permutation of `myapp-<source-repo-commit-sha>` & `<deployment-repo-commit-sha>`. 

# Proposal

Two changes:
* Keep the ability to subscribe to the image registry and configure Kargo to populate the Freights line with freights commits only. 
* Git subscription should produce Freights with images information to enable `kustomize edit image set` promotions

I would argue that both enhancements should be the default behavior.

**Comment by krancour** [comment]
> engineers keep making code changes and some automated process bump images in env/dev folder.

"Some automated process" is supposed to be Kargo. You aren't supposed to need other automation. Kargo sees new image(s) and on promotion to a given stage, mixes those in with the manifests for that stage.

> The main difference is the list of "freights" is in Git only. I personally would not benefit from the ability to pick a permutation of myapp-<source-repo-commit-sha> & <deployment-repo-commit-sha>.

I'm not sure I completely understand this statement, but if the meaning is that a lot of useless permutations may occur, I agree.

> Keep the ability to subscribe to the image registry and configure Kargo to populate the Freights line with freights commits only.

I don't know what a "freight commit" is, but again... trying to infer meaning here, I think you want some signal from the developer that the manifests are "ready." That was my intent behind #816 

I would be interested in knowing if you think #816 moves us closer to what you have in mind.

**Comment by alexmt** [comment]
> but if the meaning is that a lot of useless permutations may occur, I agree.

Correct, I just don't want to see permutations with images.

> I would be interested in knowing if you think https://github.com/akuity/kargo/issues/816 moves us closer to what you have in mind.

It is kind of a step forward, but to be honest, I view it as a workaround. I'm hoping that kargo provide first-class support for workflow: commit to `env/test` N times, then promote changes to `env/stage` -> `env/prod` while running necessary checks in between. Introducing additional branches, git tags is a necessary evil that I'm trying to avoid.

**Comment by jessesuen** [comment]
I can provide some more context, since I already discussed the use case with Alex offline, and he doesn't mind me paraphrasing.

> Keep the ability to subscribe to the image registry and configure Kargo to populate the Freights line with freights commits only.

The idea behind this is: some users may not find value in a **_multi-subscription_** zero-environment that subscribes to both image repos and git repos, and then kargo permutating the combination of them for purposes of promotion. For these users, they **_only_** want git subscription (because to them, image tag updates are no different than manifest changes). Now, the problem is that they still need a tool for that git repo to receive image tag updates automatically.

Now as it stands, Kargo can do that image tag writeback already, but it does require your zero environment to have two subscriptions, and does the permutation thing that @alexmt wouldn't use. The proposal is: we support **automated image writeback to git repos**, but following that, the change is treated no differently than a human also making env changes. I suppose you could accomplish his use case today by having a detached "image writeback" Stage, independent of the main pipeline, but it would be considered a workaround to a formalized feature. I will file a separate issue for this.

> Git subscription should produce Freights with images information to enable kustomize edit image set promotions

When I pressed him on this, this one @alexmt admits is not fully thought out. And will require a lot more discussion. But the idea is that **_if we extract image tags out of the git commit_**, we could now promote images using `kustomize edit set image`, as opposed to re-targeting a git SHA of what argo-cd syncs to. I don't know how this would work, but I will leave this issue as the one that tracks the request.

Finally, there is a third implicit feature request that isn't mentioned here (that I will also file separately) about extracting image tags as metadata in git subscription Freight, purely for **_visibility** in the UI of what's getting promoted. Because currently, what gets promoted from git subscriptions is a bit of mystery without digging into the github url. The feature would be" that we would know more information about the contents of the YAML other than the git message at Kargo UI, namely image tag they care about.

**Comment by jessesuen** [comment]
As for what to do with this issue, and the premise of the title: "Freights line combined of freights permutations from multiple subscriptions is questionable"

I personally see value in having permutations in freight and wrapping it as a deployable unit. I'd be against any proposal to remove the functionality. With that said, I don't think we need to **_force users_** to use multi-subscription as the only way to achieve certain use cases. And that is why these two feature requests are desired:
* https://github.com/akuity/kargo/issues/835
* https://github.com/akuity/kargo/issues/836

BTW, if I were to try and convince you, I think a better example of when Freight permutation would be useful is permutating two image tags from two container repos. To me, that is more useful than permutating git manifests x image tags.

**Comment by alexmt** [comment]
I totally agree that there are use cases where Freight permutation is a useful feature. So, I'm not proposing to remove it.

I just think image promotion between environments is an extremely important use case. We've seen a LOT of people automating it using CI. So I'm trying to find a way to support it with the best possible user experience.

**Comment by krancour** [comment]
Ok. I understand this better now. #835 and #836 make sense to me. Should we close this one?

**Comment by jessesuen** [comment]
> Should we close this one?

I think @alexmt may want to keep this open because I think he's still trying to find ways to *avoid* permutation, but still promote images from git. But I'll leave it to him to figure out a proposal. Also, this would not be a near-term thing. 

https://github.com/akuity/kargo/issues/835 and https://github.com/akuity/kargo/issues/836 are clear, non-controversial wins that we can do sooner vs. later, and so why I wanted to split them out from here.

**Comment by krancour** [comment]
Let's also consider the role #816 could play in reducing those unwanted permutations.

**Comment by alexmt** [comment]
I thought more about part 2 of the proposal:

> Git subscription should produce Freights with images information to enable kustomize edit image set promotions

We could allow subscribing to images only from Git repository. E.g.

```yaml
  subscriptions:
    repos:
      git:
         images:
          - repoURL: nginx
            semverConstraint: ^1.24.0
        sha: false

```
