### ISSUE TITLE
Support image writeback without image subscription

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#835]
Spawned from https://github.com/akuity/kargo/issues/832

Some users may only want git subscription (because to them, image tag updates are no different than manifest changes). The problem is that they still need a tool for that git repo to receive image tag updates automatically. Kargo can do that image tag writeback already, but it does require your zero environment to have two subscriptions. And so, it would result in Freight permutation thing that the user may not want.

The proposal is: we support automated image writeback to git repos but not result in freight permutation. In this way, the freight is nothing but git commits instead of git commits + image tags.

I think we **_could_** accomplish this use case today by having a detached "image writeback" Stage, independent of the main pipeline, but I consider a workaround to a formalized feature.

**Comment by krancour** [comment]
Ok. This is making more sense to me now than #832 did initially.

I can see the utility in this because if I rewind a year+ to when we started on all of this, this was my initial thought as well -- that I don't personally care about subscribing to _image repos_ because if I wanted to update to a new image, I'd have done it in git, so subscribing to the git repo is _all_ I really care about... but of course I'd want those changes to the git repo automated.

(On the flip side, the very existence of Image Updater proves that not everyone shares that opinion.)

Anyway... ACK on the need for this.

I do think that this is an _entirely_ different kind of automation from what Kargo does now. It's far simpler. There's no pipeline. It's _pre-pipeline_. It's watch this/these image repo(s) and update `main` accordingly... I think that's it. I would propose building this into Kargo, but having it be an entirely separate feature with its own dedicated CRDs, UI views, etc., as opposed to trying to somehow graft this on to what we've already done.

**Comment by jessesuen** [comment]
>  There's no pipeline. It's pre-pipeline. I would propose building this into Kargo, but having it be an entirely separate feature with its own dedicated CRDs, UI views, etc., as opposed to trying to somehow graft this on to what we've already done.

Great! I think you, @alexmt and I are on the same page about this. We all agree it's tangential to the pipeline and configured separately.
