### ISSUE TITLE
add support for managing repository credentials

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#886]
In the UI there is only a reference for Kargo Projects

add a repo with all the 3 types: git, image, or helm, and their state

and a borrowed repos from argoCD

**Comment by krancour** [comment]
Ya. This is something that is conspicuously absent.

> Add in the UI repo menu with sub menus for each type

> In the UI there is only a reference for Kargo Projects

Kargo handles multi-tenancy differently than Argo CD. We use specially labeled namespaces as project boundaries / units of tenancy, so with that in mind, this shouldn't be another top-level sidebar option like it is in Argo CD. Repo credentials should be configured somewhere _under_ an individual project view. I really don't want to get deep into design here, but it may be that the individual project view ends up with tabs at the top for pipelines, credentials, and other things we add over time. I know there will be more.

As a matter of terminology, and @jessesuen could weigh in, I'm not sure I'd want to stick with the "repo" terminology that Argo CD uses. imho, the purpose of "repos" in Argo CD would have been more intuitively understood if they'd been called "credentials" or even "repo credentials."

Last, but not least, this is a farther reaching change than just the UI, because the API server and CLI also lack any kind of  support for this right now. So this is an _epic_ (which could potentially be the theme of an entire minor release), so I'm going to edit the issue title to reflect this.

**Comment by krancour** [comment]
Closing in favor of #1444
